sudo: required
services:
   - docker
before_install:
   - docker build -t roshan1892/react-test -f ./client/Dockerfile.dev ./client
script:
   - docker run roshan1892/react-test npm test -- --coverage
     mvn install.travis_wait
after_success:
   - docker build -t roshan1892/multi-client ./client     
   - docker build -t roshan1892/multi-nginx ./nginx     
   - docker build -t roshan1892/multi-server ./server     
   - docker build -t roshan1892/multi-worker ./worker     

#Login to Docker CLI before attempting to push images to DockerHub
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   
#Take those images and push them to docker hub
   - docker push roshan1892/multi-client
   - docker push roshan1892/multi-nginx
   - docker push roshan1892/multi-server
   - docker push roshan1892/multi-worker 